[package]
name = "day-001"
version = "0.1.0"
authors = ["Marcel Araujo <ceceldada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
